import type { Multilingual } from "./multilingual";

export type BlogCategory = "updates" | "achievements" | "collaborations";

export interface BlogPost {
  id: string;
  slug: string;
  category: BlogCategory;
  date: string; // ISO
  image: string;
  title: Multilingual;
  excerpt: Multilingual;
  content: Multilingual;
}

const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1200&q=70`;

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "najmah-launches-arabic-stories",
    category: "updates",
    date: "2026-04-10",
    image: img("1512820790803-83ca734da794"),
    title: {
      en: "Najmah launches a brand new Arabic stories collection ✨",
      ar: "نجمة تطلق مجموعة قصص عربية جديدة كلياً ✨",
    },
    excerpt: {
      en: "Twelve magical bedtime stories, fully narrated in Arabic, are now live on the platform.",
      ar: "اثنتا عشرة قصة سحرية لما قبل النوم، مسرودة بالكامل بالعربية، متاحة الآن على المنصة.",
    },
    content: {
      en: "We are thrilled to share that our Arabic stories collection just went live! Twelve hand-crafted bedtime tales, fully narrated by warm voices, are ready to spark your child's imagination. Each story is paired with a beautiful illustration and gentle background music for the perfect bedtime experience.",
      ar: "يسعدنا أن نعلن عن إطلاق مجموعتنا الجديدة من القصص العربية! اثنتا عشرة قصة لما قبل النوم، مصممة بعناية ومسرودة بأصوات دافئة، جاهزة لإشعال خيال طفلك. كل قصة مصحوبة برسوم توضيحية جميلة وموسيقى هادئة لتجربة نوم مثالية.",
    },
  },
  {
    id: "2",
    slug: "10000-stories-milestone",
    category: "achievements",
    date: "2026-04-02",
    image: img("1481627834876-b7833e8f5570"),
    title: {
      en: "We just crossed 10,000 stories generated by kids 🎉",
      ar: "تجاوزنا ١٠،٠٠٠ قصة أنشأها الأطفال 🎉",
    },
    excerpt: {
      en: "A massive thank-you to every little storyteller out there. Here's what we learned.",
      ar: "شكر كبير لكل راوٍ صغير. إليك ما تعلمناه.",
    },
    content: {
      en: "What a milestone! Together with thousands of families around the world, the AI Storyteller has now created over ten thousand personalized bedtime stories. The most popular themes? Brave dragons, underwater kingdoms, and intergalactic friendships. Thank you for trusting Najmah with your bedtime moments.",
      ar: "يا له من إنجاز! بالتعاون مع آلاف العائلات حول العالم، أنشأ الراوي الذكي أكثر من عشرة آلاف قصة مخصصة لما قبل النوم. الموضوعات الأكثر شعبية؟ التنانين الشجاعة، والممالك تحت الماء، والصداقات بين المجرات. شكراً لثقتكم بنجمة في لحظات النوم.",
    },
  },
  {
    id: "3",
    slug: "partnership-with-cairo-libraries",
    category: "collaborations",
    date: "2026-03-25",
    image: img("1507842217343-583bb7270b66"),
    title: {
      en: "New partnership with Cairo Public Libraries 📚",
      ar: "شراكة جديدة مع مكتبات القاهرة العامة 📚",
    },
    excerpt: {
      en: "Free Najmah access for every child registered at Cairo's public libraries.",
      ar: "وصول مجاني لنجمة لكل طفل مسجل في مكتبات القاهرة العامة.",
    },
    content: {
      en: "We are proud to announce our partnership with Cairo Public Libraries. Every child holding a library card will receive a free Najmah account, including unlimited access to our story library and the AI Storyteller. Reading should be a right, not a privilege.",
      ar: "نفخر بالإعلان عن شراكتنا مع مكتبات القاهرة العامة. كل طفل يحمل بطاقة مكتبة سيحصل على حساب نجمة مجاني، بما في ذلك وصول غير محدود لمكتبة القصص والراوي الذكي. القراءة حق، لا امتياز.",
    },
  },
  {
    id: "4",
    slug: "drawing-contest-april-winners",
    category: "achievements",
    date: "2026-03-18",
    image: img("1503454537195-1dcabb73ffb9"),
    title: {
      en: "Meet the April drawing contest winners 🏆",
      ar: "تعرّفوا على الفائزين بمسابقة الرسم لشهر أبريل 🏆",
    },
    excerpt: {
      en: "Three incredible artists, three magical themes, one celebration.",
      ar: "ثلاثة فنانين موهوبين، ثلاثة موضوعات سحرية، احتفال واحد.",
    },
    content: {
      en: "Congratulations to Yara, Omar, and Lina — our April winners! Their stunning drawings on the theme \"Magical Dreams\" reminded us why we built this platform. New monthly themes coming soon.",
      ar: "تهانينا ليارا وعمر ولينا — فائزو شهر أبريل! رسوماتهم المذهلة حول موضوع «أحلام سحرية» ذكّرتنا لماذا بنينا هذه المنصة. موضوعات شهرية جديدة قريباً.",
    },
  },
  {
    id: "5",
    slug: "new-language-french",
    category: "updates",
    date: "2026-03-08",
    image: img("1488646953014-85cb44e25828"),
    title: {
      en: "Bonjour! French stories are now available 🇫🇷",
      ar: "بونجور! القصص الفرنسية متاحة الآن 🇫🇷",
    },
    excerpt: {
      en: "Najmah now speaks six languages — French is the latest addition.",
      ar: "نجمة تتحدث الآن ست لغات — الفرنسية هي أحدث إضافة.",
    },
    content: {
      en: "We're expanding! French now joins our language family alongside Arabic, English, German, Italian, and Spanish. Every story in our library is being translated and re-narrated by native speakers.",
      ar: "نحن نتوسع! انضمت الفرنسية الآن إلى عائلة لغاتنا بجانب العربية والإنجليزية والألمانية والإيطالية والإسبانية. كل قصة في مكتبتنا تُترجم ويُعاد سردها بأصوات الناطقين الأصليين.",
    },
  },
  {
    id: "6",
    slug: "school-program-launch",
    category: "collaborations",
    date: "2026-02-22",
    image: img("1503676260728-1c00da094a0b"),
    title: {
      en: "Najmah for Schools is here 🏫",
      ar: "نجمة للمدارس وصلت 🏫",
    },
    excerpt: {
      en: "A dedicated program for classrooms with teacher dashboards and reading challenges.",
      ar: "برنامج مخصص للفصول الدراسية مع لوحات معلمين وتحديات قراءة.",
    },
    content: {
      en: "Teachers, this one's for you. Najmah for Schools includes a teacher dashboard, reading challenges, classroom-wide story creation, and detailed engagement reports. Pilot schools are already onboard — apply for the next cohort.",
      ar: "أيها المعلمون، هذا لكم. نجمة للمدارس تشمل لوحة معلم، وتحديات قراءة، وإنشاء قصص جماعي للفصل، وتقارير تفاعل مفصلة. مدارس تجريبية بدأت بالفعل — تقدّموا للدفعة القادمة.",
    },
  },
];

export const blogStats = {
  totalStories: 312,
  totalUsers: 8740,
  totalDrawings: 1265,
};
