project_id = "obafpnloxexvyiodpsxz"

[functions.paddle-webhook]
verify_jwt = false

[functions.paddle-config]
verify_jwt = false


[functions.send-welcome-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

