export const CREDIT_COSTS = {
  STORY_GENERATION: 1,
  ILLUSTRATION_GENERATION: 1,
  PDF_EXPORT: 1,
};

export const TRANSACTION_TYPES = {
  INITIAL_GRANT: 'INITIAL_GRANT',
  STORY_GENERATION: 'STORY_GENERATION',
  ILLUSTRATION_GENERATION: 'ILLUSTRATION_GENERATION',
  PDF_EXPORT: 'PDF_EXPORT',
  BONUS: 'BONUS',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
};

export const USAGE_EVENTS = {
  STORY_CREATED: 'STORY_CREATED',
  ILLUSTRATION_JOB_STARTED: 'ILLUSTRATION_JOB_STARTED',
  PDF_EXPORTED: 'PDF_EXPORTED',
};
