import { Injectable, Inject, Logger } from '@nestjs/common';
import { StoryContextBuilder } from '../context/story-context.builder.js';
import { PromptBuilder } from '../prompts/prompt.builder.js';
import { LLM_PROVIDER } from '../interfaces/llm-provider.interface.js';
import type { LLMProvider } from '../interfaces/llm-provider.interface.js';
import { StoryPlan } from '../interfaces/story-plan.interface.js';

import {
  AIProviderException,
  AIProviderUnavailableException,
  AIParseException,
  AIValidationException,
} from '../exceptions/ai.exceptions.js';

@Injectable()
export class StoryPlanner {
  private readonly logger = new Logger(StoryPlanner.name);

  constructor(
    private readonly contextBuilder: StoryContextBuilder,
    private readonly promptBuilder: PromptBuilder,
    @Inject(LLM_PROVIDER) private readonly llmProvider: LLMProvider,
  ) {}

  /**
   * Orchestrates the planning phase of the SEL pipeline.
   * Transforms a basic request into a structured 4-act StoryPlan.
   */
  async planStory(
    childAge: number,
    language: string,
    theme: string,
    selGoal: string,
    readingLevel: string,
  ): Promise<StoryPlan> {
    this.logger.log(`Building story context`);

    // 1. Build unified context
    const context = this.contextBuilder.build(
      childAge,
      language,
      theme,
      selGoal,
      readingLevel,
    );

    // 2. Generate Prompt
    const prompt = this.promptBuilder.buildPlannerPrompt(context);
    this.logger.debug(`Generated planner prompt`);

    // 3. Request LLM Generation
    let rawResponse: string;
    try {
      rawResponse = await this.llmProvider.generateBlueprint(prompt);
    } catch (error) {
      // A temporary provider outage must keep its retryable identity so the
      // HTTP layer answers 503 + AI_PROVIDER_TEMPORARILY_UNAVAILABLE.
      if (error instanceof AIProviderUnavailableException) {
        this.logger.warn(
          JSON.stringify({
            event: 'ai_provider_unavailable',
            stage: 'planner',
            ...error.meta,
          }),
        );
        throw error;
      }
      this.logger.error('Provider failed during blueprint generation', error);
      throw new AIProviderException('Failed to generate blueprint', error);
    }

    // 4. Parse the JSON Output
    let parsedPlan: any;
    try {
      parsedPlan = JSON.parse(rawResponse);
    } catch (error) {
      this.logger.error('Failed to parse AI response as JSON', error);
      throw new AIParseException(
        'Invalid JSON generated by provider',
        rawResponse,
      );
    }

    // 5. Validate the structured data matches StoryPlan
    this.validatePlan(parsedPlan);

    this.logger.log(
      `Successfully generated valid StoryPlan: ${parsedPlan.title}`,
    );
    return parsedPlan as StoryPlan;
  }

  private validatePlan(plan: any): void {
    const requiredFields = [
      'title',
      'characters',
      'conflict',
      'resolution',
      'selGoals',
      'pageCount',
    ];
    for (const field of requiredFields) {
      if (plan[field] === undefined) {
        throw new AIValidationException(
          `Missing required field: ${field}`,
          plan,
        );
      }
    }
  }
}
