import { Injectable, Inject, Logger } from '@nestjs/common';
import { PromptBuilder } from '../prompts/prompt.builder.js';
import { LLM_PROVIDER } from '../interfaces/llm-provider.interface.js';
import type { LLMProvider } from '../interfaces/llm-provider.interface.js';
import { StoryPlan } from '../interfaces/story-plan.interface.js';
import { StoryContext } from '../context/story-context.interface.js';
import { GeneratedStory } from '../interfaces/generated-story.interface.js';
import {
  AIProviderException,
  AIParseException,
  AIValidationException,
} from '../exceptions/ai.exceptions.js';

@Injectable()
export class StoryWriter {
  private readonly logger = new Logger(StoryWriter.name);

  constructor(
    private readonly promptBuilder: PromptBuilder,
    @Inject(LLM_PROVIDER) private readonly llmProvider: LLMProvider,
  ) {}

  /**
   * Orchestrates the writing phase of the SEL pipeline.
   * Transforms the blueprint and context into the actual prose of the story.
   */
  async writeStory(
    context: StoryContext,
    plan: StoryPlan,
  ): Promise<GeneratedStory> {
    this.logger.log(`Building writer prompt for: ${plan.title}`);

    // 1. Generate Prompt
    const prompt = this.promptBuilder.buildWriterPrompt(context, plan);
    this.logger.debug(`Generated writer prompt`);

    // 2. Request LLM Generation
    let rawResponse: string;
    try {
      rawResponse = await this.llmProvider.generateStory(prompt);
    } catch (error) {
      this.logger.error('Provider failed during story writing', error);
      throw new AIProviderException('Failed to generate story text', error);
    }

    // 3. Parse the JSON Output
    let parsedStory: any;
    try {
      parsedStory = JSON.parse(rawResponse);
    } catch (error) {
      this.logger.error('Failed to parse AI story response as JSON', error);
      throw new AIParseException(
        'Invalid JSON generated by provider during writing',
        rawResponse,
      );
    }

    // 4. Validate the structured data matches GeneratedStory
    this.validateStory(parsedStory);

    this.logger.log(
      `Successfully generated story prose with ${parsedStory.pages.length} pages.`,
    );
    return parsedStory as GeneratedStory;
  }

  private validateStory(story: any): void {
    if (!story.title) {
      throw new AIValidationException(`Missing required field: title`, story);
    }
    if (!story.metadata || !story.metadata.theme || !story.metadata.selGoal) {
      throw new AIValidationException(`Missing or invalid metadata`, story);
    }
    if (!story.pages || !Array.isArray(story.pages)) {
      throw new AIValidationException(`Missing pages array`, story);
    }
    if (story.pages.length === 0) {
      throw new AIValidationException(`Pages array is empty`, story);
    }
    for (const page of story.pages) {
      if (typeof page.pageNumber !== 'number' || !page.text) {
        throw new AIValidationException(
          `Invalid page format in pages array`,
          story,
        );
      }
    }
  }
}
