from pydantic import BaseModel, Field
from typing import List

class GeneratedStory(BaseModel):
    """Full story content generated by the writer (placeholder)."""
    title: str = Field(..., description="Story title")
    pages: List[str] = Field(..., description="List of page texts in order")
    selGoals: List[str] = Field(..., description="SEL objectives addressed in the story")
